title: "Kollegorna Labs"

description: "We build stuff with Rails, Ember.js, Node.js and Go. This is our messy lab…"

image: "https://www.kollegorna.se/images/kollegorna-facebook-avatar.png"

twitter: "@Kollegorna"
