# Paths
source:      ./app
destination: ./dist

# Setup
name: Kollegorna Labs
permalink: /blog/:year/:month/:title/
url: http://labs.kollegorna.se
gems: [sass, compass, breakpoint, uglifier, jekyll-assets, jekyll-assets/compass]
markdown: redcarpet
pygments: true
paginate: 9
paginate_path: "blog/page:num"

# Jekyll Assets configuration
# https://github.com/ixti/jekyll-assets
assets:
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/vendor
  js_compressor:  uglifier
  css_compressor: sass
